package cod.ast;

public enum NodeKind {
    PROGRAM, UNIT, USE,
    TYPE, FIELD, METHOD, PARAM, CONSTRUCTOR, CONSTRUCTOR_CALL,
    POLICY, POLICY_METHOD,
    BLOCK, ASSIGNMENT, VAR, STMT_IF, EXPR_IF, FOR, SKIP, BREAK,
    RANGE, EXIT, TUPLE,
    RETURN_SLOT_ASSIGNMENT, SLOT_DECLARATION, SLOT_ASSIGNMENT, MULTIPLE_SLOT_ASSIGNMENT,
    BINARY_OP, UNARY, TYPE_CAST, METHOD_CALL, ARRAY,
    INDEX_ACCESS, RANGE_INDEX, MULTI_RANGE_INDEX,
    EQUALITY_CHAIN, BOOLEAN_CHAIN,
    SLOT, LAMBDA, PROPERTY_ACCESS,
    IDENTIFIER, INT_LITERAL, FLOAT_LITERAL, TEXT_LITERAL, BOOL_LITERAL, NONE_LITERAL,
    THIS, SUPER
}
