# unit test
timestamp = "1775052835598"
generator = "Coderive 1.0"

[classes]
Accept = "Policy.cod"
Broadcaster = "Broadcast.cod"
Hello = "Import.cod"
Hello1 = "LazyLoop.cod"
IOTest = "IO.cod"
Intective = "Interactive.cod"
LazyLoop = "LazyLoop.cod"
LoopWithIOTest = "Loop.cod"
Main = "Policy.cod"
Node = "Policy.cod"
ParameterSkippingDemo = "ParamSkip.cod"
Test1 = "Basic.cod"
