# unit math
timestamp = "1775972663363"
generator = "Coderive 1.0"

[classes]
Core = "Math.cod"
LinearAlgebra = "LinearAlgebra.cod"
NumberTheory = "NumberTheory.cod"
Random = "Random.cod"
Stats = "Stats.cod"
Trig = "Trig.cod"
