# unit scimath
timestamp = "1775972663392"
generator = "Coderive 1.0"

[classes]
Airy = "Methods.cod"
Bernoulli = "Methods.cod"
Bessel = "Methods.cod"
Binomial = "Methods.cod"
Complex = "Complex.cod"
Convolution = "Methods.cod"
Elliptic = "Methods.cod"
ErrorFunction = "Methods.cod"
Geometric = "Methods.cod"
Integration = "Methods.cod"
Interpolation = "Methods.cod"
LogNormal = "Methods.cod"
ODE = "Methods.cod"
Pareto = "Methods.cod"
SciMath = "SciMath.cod"
Spectral = "Methods.cod"
Weibull = "Methods.cod"
Window = "Methods.cod"
