# unit test
timestamp = "1775630272432"
generator = "Coderive 1.0"

[classes]
Accept = "Policy.cod"
AutoCurrying = "AutoCurrying.cod"
AutoStackingNumberComprehensive = "AutoStackingNumberComprehensive.cod"
AutoStackingNumberEdgeCases = "AutoStackingNumberEdgeCases.cod"
BreakSkipDemo = "BreakSkip.cod"
Broadcaster = "Broadcast.cod"
ConstantReassignmentInvalid = "ConstantReassignmentInvalid.cod"
ConstantRequiresInitializerInvalid = "ConstantRequiresInitializerInvalid.cod"
ControlFlow = "ControlFlow.cod"
Hello = "Import.cod"
Hello1 = "LazyLoop.cod"
HelloWorldModule = "HelloWorldModule.cod"
IOTest = "IO.cod"
Intective = "Interactive.cod"
InternalRangeSpecImport = "InternalRangeSpecImport.cod"
IsAndUnionDemo = "IsAndUnion.cod"
LambdaDemo = "Lambda.cod"
LazyLoop = "LazyLoop.cod"
LoopWithIOTest = "Loop.cod"
Main = "Policy.cod"
Named = "OOPConstructor.cod"
Node = "Policy.cod"
NoneAndTypeDemo = "NoneAndType.cod"
OOPCtorMain = "OOPConstructor.cod"
ParameterSkippingDemo = "ParamSkip.cod"
Parent = "SuperThis.cod"
SelfCallInvalidNoParentheses = "SelfCallInvalidNoParentheses.cod"
SelfCallLambda = "SelfCallLambda.cod"
SelfCallLambdaConstantLevel = "SelfCallLambdaConstantLevel.cod"
SelfCallLambdaLevels = "SelfCallLambdaLevels.cod"
SelfCallLevelConstantInMethodInvalid = "SelfCallLevelConstantInMethodInvalid.cod"
SelfCallLevelInMethodInvalid = "SelfCallLevelInMethodInvalid.cod"
SelfCallMethod = "SelfCallMethod.cod"
SuperThisMain = "SuperThis.cod"
TailCallOptimization = "TailCallOptimization.cod"
Test1 = "Basic.cod"
TextLiteral = "TextLiteral.cod"
TypeAndTupleDemo = "TypeAndTuple.cod"
