package cod;

public class Constants {

    public static final String
            share = "share",
            local = "local",
            unit = "unit",
            get = "get",
            extend = "extend",
            this_ = "this",
            var = "var",
            input_ = "input",
            output = "output",
            if_ = "if",
            else_ = "else",
            elif_ = "elif",
            for_ = "for",
            in_ = "in",
            to_ = "to",
            by_ = "by",
            int_ = "int",
            string = "string",
            float_ = "float",
            bool = "bool",
            true_ = "true",
            false_ = "false",
            builtin = "builtin",
            all = "all",
            any = "any"
            ;
    
    public static final String
            _share = "share", 
            _local = "LOCAL",
            _unit = "UNIT",
            _get = "GET",
            _extend = "EXTEND",
            _this = "THIS",
            _var = "VAR",
            _output = "OUTPUT",
            _input = "INPUT",
            _if = "IF",
            _else = "ELSE",
            _elif = "ELIF",
            _for = "FOR",
            _in = "IN",
            _to = "TO",
            _by = "BY",
            _int = "INT",
            _string = "STRING",
            _float = "FLOAT",
            _bool = "BOOL",
            _eof = "EOF",
            _int_lit = "INT_LIT",
            _float_lit = "FLOAT_LIT",
            _string_lit = "STRING_LIT",
            _bool_lit = "BOOL_LIT",
            _id = "ID",
            _assign = "ASSIGN",
            _plus = "PLUS",
            _minus = "MINUS",
            _mul = "MUL",
            _div = "DIV",
            _mod = "MOD",
            _colon = "COLON",
            _gt = "GT",
            _lt = "LT",
            _gte = "GTE",
            _lte = "LTE",
            _eq = "EQ",
            _neq = "NEQ",
            _dot = "DOT",
            _comma = "COMMA",
            _lparen = "LPAREN",
            _rparen = "RPAREN",
            _lbrace = "LBRACE",
            _rbrace = "RBRACE",
            _lbracket = "LBRACKET",
            _rbracket = "RBRACKET",
            _plus_assign = "PLUS_ASSIGN",
            _minus_assign = "MINUS_ASSIGN",
            _mul_assign = "MUL_ASSIGN",
            _div_assign = "DIV_ASSIGN",
            _builtin = "BUILTIN",
            _all = "ALL",
            _any = "ANY",
            _bang = "BANG",
            _tilde_bar = "TILDE_BAR",
            _tilde_arrow = "TILDE_ARROW",
            _line_comment = "LINE_COMMENT",
            _block_comment = "BLOCK_COMMENT",
            _ws = "WS",
            _invalid = "INVALID"
            ;
}