name: Quick Test

on: [pull_request]

jobs:
  quick-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
    - name: Quick build test
      run: |
        find src/main/java -name "*.java" > sources.txt
        mkdir -p target/classes
        javac -d target/classes @sources.txt
        # Test with first .cdrv file found
        TEST_FILE=$(find src/main/cdrv -name "*.cdrv" -type f | head -1)
        if [ -n "$TEST_FILE" ]; then
          java -cp target/classes cdrv.runner.CompilerRunner --bytecode "$TEST_FILE"
        fi